vim.keymap.set({ "n", "x" }, "j", "v:count == 0 ? 'gj' : 'j'", { desc = "Down", expr = true, silent = true })
vim.keymap.set({ "n", "x" }, "k", "v:count == 0 ? 'gk' : 'k'", { desc = "Up", expr = true, silent = true })
vim.keymap.set("n", "<leader>w", "<cmd>write<CR>", { desc = "Save File" })
vim.keymap.set("n", "<leader>q", "<cmd>quit!<CR>", { desc = "Quit" })
vim.keymap.set("n", "<leader>bd", "<cmd>bd<CR>", { desc = "Buffer Delete" })
vim.keymap.set("n", "<leader>bo", "<cmd>%bd|e#<CR>", { desc = "Buffer Delete Other" })
vim.keymap.set("n", "<leader>ba", "<cmd>%bd<CR>", { desc = "Buffer Delete All" })
vim.keymap.set("n", "<leader>o", "<cmd>update<CR> :source<CR>", { desc = "Source File" })
vim.keymap.set("n", "<leader>e", "<cmd>Oil<CR>", { desc = "Oil" })
vim.keymap.set({ "n", "v", "x" }, "<leader>y", [["+y]], { desc = "Yank Clipboard" })
vim.keymap.set({ "n", "v", "x" }, "<leader>p", [["+p]], { desc = "Paste Clipboard" })
vim.keymap.set({ "n", "v", "x" }, "<leader>d", [["_d]], { desc = "Delete into void" })
vim.keymap.set("v", "<", "<gv", { desc = "Indent left and reselect" })
vim.keymap.set("v", ">", ">gv", { desc = "Indent right and reselect" })

vim.keymap.set("v", "<S-j>", ":<C-u>execute \"'<,'>move '>+\" . v:count1<cr>gv=gv", { desc = "Move Down" })
vim.keymap.set("v", "<S-k>", ":<C-u>execute \"'<,'>move '<-\" . (v:count1 + 1)<cr>gv=gv", { desc = "Move Up" })
vim.keymap.set("n", "<C-d>", "<C-d>zz", { desc = "Center cursor after moving down half-page" })
vim.keymap.set("n", "<C-u>", "<C-u>zz", { desc = "Center cursor after moving up half-page" })
vim.keymap.set("n", "n", "nzz", { desc = "Center cursor after checking the next match" })
vim.keymap.set("n", "N", "Nzz", { desc = "Center cursor after checking the previous match" })
vim.keymap.set("n", "J", "mzJ`z", { desc = "Concat lines inplace" })
vim.keymap.set("n", "<leader>ce", "oif err != nil {<CR>return nil, err<CR>}<ESC>k$", { desc = "Go iferr" })
vim.keymap.set("n", "<leader>cx", "<cmd>!go run %<CR>", { desc = "Run go code" })
vim.keymap.set("n", "<leader>r", vim.lsp.buf.rename, { desc = "Rename" })
vim.keymap.set("n", "<C-j>", "<cmd>cnext<CR>", { desc = "Quickfix Next" })
vim.keymap.set("n", "<C-k>", "<cmd>cprev<CR>", { desc = "Quickfix Prev" })

vim.keymap.set("v", "<leader>cs", function()
	vim.cmd('normal! "zy')
	local pattern = vim.fn.escape(vim.fn.getreg("z"), "\\/.*$^~[]")
	local cmd = ":s/" .. pattern .. "//gI"
	local keys = vim.api.nvim_replace_termcodes(cmd .. "<Left><Left><Left>", true, false, true)
	vim.fn.feedkeys(keys, "t")
end, { desc = "Substitute selection in line" })

vim.keymap.set("v", "<leader>cgs", function()
	vim.cmd('normal! "zy')
	local pattern = vim.fn.escape(vim.fn.getreg("z"), "\\/.*$^~[]")
	local cmd = ":%s/" .. pattern .. "//gI"
	local keys = vim.api.nvim_replace_termcodes(cmd .. "<Left><Left><Left>", true, false, true)
	vim.fn.feedkeys(keys, "t")
end, { desc = "Substitute selection in file" })

vim.keymap.set("n", "<leader>cu", "<cmd>s//\\u~/i<CR>", { desc = "Case switched recent substitution" })
vim.keymap.set("n", "<leader>cgu", "<cmd>%s//\\u~/i<CR>", { desc = "Case switched global recent substitution" })

vim.keymap.set("n", "<leader>ct", "<cmd>!go mod tidy<CR>", { desc = "Go mod tidy" })
